### ISSUE TITLE
Webshop

### ISSUE THREAD

**Issue by knacker** [kulkeeli/Blau-Weiss-Eichwege-SV#1]
Please give more details about the Webshop. The information you provided there is not precise enough to tell me, how it should look like.

**Comment by kulkeeli** [comment]
Hello,

I have uploaded the layout of the webshop. You can use the second article as your placeholder. size-Input should be a dropdown menu where you can choose from XXS to XXL and for the amount-input the user may enter a number by themself. Also please make the Buy-Button so that it stands out.

**Comment by knacker** [comment]
That explains the Looks very good, thanks. What I didn't Unterstand yet was: do you just want the empty Shop, exactly as shown in the picture, or should it already contain some items?

**Comment by kulkeeli** [comment]
You only need to add the placeholder as an item so that we see how the articles will look like. The shop itself, however, is empty. 

I forgot to tell you to add the content of the readme so that people now that the shop isn't done. Also disable the Buy-Button of the placeholder.
