### ISSUE TITLE
Dropping sidenav

### ISSUE THREAD

**Issue by knacker** [kulkeeli/Blau-Weiss-Eichwege-SV#7]
Hello,

I'm wondering, If it would be a problem for you, if we decided to drop the sidenavigation and instead opted for one at the top? That would make a lot of things easier for us and the Website would look a lot better too(in my opinion). 

Best Regards,
M.Raspe.

**Comment by kulkeeli** [comment]
Since Assignment 2b is over feel free to make any changes.
